spring:
  cloud:
    function:
      definition: getRecentTransactions;getFraudStatus;requestCardBlock;returnFinalResponse
    stream:
      bindings:
        getRecentTransactions-in-0:
          destination: q.fraudCheck.orchestratorService_1
          group: myconsumergroup
          binder: solace-broker
        getRecentTransactions-out-0:
          # The function will generate the outbound topic dynamically. This setting is not expected to be used by the binder.
          destination: topic-not-used
          binder: solace-broker
          
        getFraudStatus-in-0:
          destination: q.fraudCheck.orchestratorService_2
          group: myconsumergroup
          binder: solace-broker
        getFraudStatus-out-0:
          # The function will generate the outbound topic dynamically. This setting is not expected to be used by the binder.
          destination: topic-not-used
          binder: solace-broker   

        requestCardBlock-in-0:
          destination: q.fraudCheck.orchestratorService_3
          group: myconsumergroup
          binder: solace-broker
        requestCardBlock-out-0:
          # The function will generate the outbound topic dynamically. This setting is not expected to be used by the binder.
          destination: topic-not-used
          binder: solace-broker      
          
        returnFinalResponse-in-0:
          destination: q.fraudCheck.orchestratorService_4
          group: myconsumergroup
          binder: solace-broker
        returnFinalResponse-out-0:
          # The function will generate the outbound topic dynamically. This setting is not expected to be used by the binder.
          destination: topic-not-used
          binder: solace-broker               
      binders:  
      #This section of the configuration tells the solace binder how to connect to the solace event broker/mesh 
        solace-broker:  
          type: solace 
          environment: 
            solace: 
              java: 
                host: tcps://public-demo-broker.messaging.solace.cloud:55443 
                msgVpn: cloud-demo-solace-uk 
                clientUsername: scs-demo-public-user 
                clientPassword: scs-demo-public-user 
                connectRetries: 3 
                connectRetriesPerHost: 0 
                reconnectRetries: 3 
      solace:
        bindings:
          getRecentTransactions-in-0:
            consumer:
              queueAdditionalSubscriptions: myBank/cards/fraudCheckApi/status/v1/>
              provisionDurableQueue: true
              queueNameExpression: destination
        
          getFraudStatus-in-0:
            consumer:
              queueAdditionalSubscriptions: myBank/cards/fraudCheckApi/reply/txnService/history/v1/>
              provisionDurableQueue: true
              queueNameExpression: destination     
              
          requestCardBlock-in-0:
            consumer:
              queueAdditionalSubscriptions: myBank/cards/fraudCheckApi/reply/fraudService/status/v1/>
              provisionDurableQueue: true
              queueNameExpression: destination     
        
          returnFinalResponse-in-0:
            consumer:
              queueAdditionalSubscriptions: myBank/cards/fraudCheckApi/reply/fraudService/status/v1/>
              provisionDurableQueue: true
              queueNameExpression: destination                              